Que4.-

The model's main purpose is to predict the 10-year risk of Coronary Heart Disease (CHD). CHD is a disease of the blood vessels supplying the heart. Heart disease has been the leading cause of death worldwide since 1921. In 2008, 7.3 million people died from CHD. 
The classification goal is to predict whether the patient has 10-year risk of future coronary heart disease (CHD).The dataset provides the patientsâ€™ information. It includes over 4,000 records and 15 attributes.
Variables
Sex: male or female(0=female, 1=male)
Age: Age of the patient
education: Some high school (1), high school/GED (2), some college/vocational school (3), college (4)
Current Smoker: whether or not the patient is a current smoker (0=No, 1=Yes)
Cigs Per Day: the number of cigarettes that the person smoked on average in one day
BP Meds: whether or not the patient was on blood pressure medication 
Prevalent Stroke: whether or not the patient had previously had a stroke (0=No, 1=Yes)
Prevalent Hyp: whether or not the patient was hypertensive (0=No, 1=Yes)
Diabetes: whether or not the patient had diabetes (0=No, 1=Yes)
Tot Chol: total cholesterol level
Sys BP: systolic blood pressure 
Dia BP: diastolic blood pressure
BMI: Body Mass Index
Heart Rate: heart rate
Glucose: glucose level

Prepare model by using Decision Tree, Random Forest, AdaBoost,CatBoost and XGBoost & Calculate Accuracy by confusion matrix, Calculate accuracy score, precision score, recall score, f1 score.

Datasets : framingham.csv

### pre-requisites

In [1]:
import warnings
warnings.filterwarnings(action="ignore")

### import required packages

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### load the data

In [3]:
df = pd.read_csv('framingham.csv')
df.head()

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0

### EDA

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4240 entries, 0 to 4239
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   male             4240 non-null   int64
 1   age              4240 non-null   int64
 2   education        4135 non-null   float64
 3   currentSmoker    4240 non-null   int64
 4   cigsPerDay       4211 non-null   float64
 5   BPMeds           4187 non-null   float64
 6   prevalentStroke  4240 non-null   int64
 7   prevalentHyp     4240 non-null   int64
 8   diabetes         4240 non-null   int64
 9   totChol          4190 non-null   float64
 10  sysBP            4240 non-null   float64
 11  diaBP            4240 non-null   float64
 12  BMI              4221 non-null   float64
 13  heartRate        4239 non-null   float64
 14  glucose          3852 non-null   float64
 15  TenYearCHD       4240 non-null   int64
dtypes: float64(9), int64(7)
memory usage: 530.1 KB

In [5]:
df.isna().sum()

male                 0
age                  0
education          105
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

In [12]:
df['cigsPerDay'] = df['cigsPerDay'].fillna(df['cigsPerDay'].mean())
df['totChol'] = df['totChol'].fillna(df['totChol'].mean())
df['BMI'] = df['BMI'].fillna(df['BMI'].mean())
df['glucose'] = df['cigsPerDay'].fillna(df['glucose'].mean())
df['heartRate'] = df['heartRate'].fillna(df['heartRate'].mean())
l = ['education','BPMeds']
for i in l:
    df[i] = df[i].fillna(df[i].mode()[0])

In [13]:
df.isna().sum()

male               0
age                0
education          0
currentSmoker      0
cigsPerDay         0
BPMeds             0
prevalentStroke    0
prevalentHyp       0
diabetes           0
totChol            0
sysBP              0
diaBP              0
BMI                0
heartRate          0
glucose            0
TenYearCHD         0
dtype: int64

In [14]:
df['TenYearCHD'].value_counts()

TenYearCHD
0    3596
1     644
Name: count, dtype: int64

In [15]:
df_minority= df[df['TenYearCHD']==1]
df_majority= df[df['TenYearCHD']==0]

In [16]:
from sklearn.utils import resample

df_up_sampled = resample(df_minority, n_samples=(3596), random_state=123456)
df_up_sampled

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
344,0,63,1.0,1,20.0,0.0,0,0,0,238.0,136.0,66.0,20.20,60.0,20.0,1
3298,0,46,3.0,1,20.0,0.0,0,0,0,267.0,119.0,65.0,29.15,83.0,20.0,1
246,0,61,3.0,0,0.0,0.0,0,1,0,189.0,133.0,83.0,22.82,87.0,0.0,1
3796,0,59,1.0,0,0.0,0.0,0,0,0,254.0,116.0,71.0,25.48,75.0,0.0,1
1044,0,65,1.0,0,0.0,0.0,1,1,0,290.0,144.0,64.0,21.41,58.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2041,1,68,1.0,0,0.0,0.0,0,1,1,184.0,157.0,97.0,33.16,110.0,0.0,1
745,0,66,1.0,0,0.0,0.0,0,1,0,232.0,175.0,94.0,29.84,95.0,0.0,1
2930,0,57,1.0,1,43.0,0.0,0,1,0,283.0,207.5,118.0,38.61,100.0,43.0,1
481,0,64,1.0,0,0.0,0.0,0,1,0,253.0,295.0,135.0,38.82,92.0,0.0,1
1674,1,56,3.0,0,0.0,0.0,0,0,1,214.0,115.0,80.0,25.09,70.0,0.0,1

In [17]:
df_balanced = pd.concat([df_up_sampled, df_majority])
df_balanced

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
344,0,63,1.0,1,20.0,0.0,0,0,0,238.0,136.0,66.0,20.20,60.0,20.0,1
3298,0,46,3.0,1,20.0,0.0,0,0,0,267.0,119.0,65.0,29.15,83.0,20.0,1
246,0,61,3.0,0,0.0,0.0,0,1,0,189.0,133.0,83.0,22.82,87.0,0.0,1
3796,0,59,1.0,0,0.0,0.0,0,0,0,254.0,116.0,71.0,25.48,75.0,0.0,1
1044,0,65,1.0,0,0.0,0.0,1,1,0,290.0,144.0,64.0,21.41,58.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4235,0,48,2.0,1,20.0,0.0,0,0,0,248.0,131.0,72.0,22.00,84.0,20.0,0
4236,0,44,1.0,1,15.0,0.0,0,0,0,210.0,126.5,87.0,19.16,86.0,15.0,0
4237,0,52,2.0,0,0.0,0.0,0,0,0,269.0,133.5,83.0,21.47,80.0,0.0,0
4238,1,40,3.0,0,0.0,0.0,0,1,0,185.0,141.0,98.0,25.60,67.0,0.0,0
4239,0,39,3.0,1,30.0,0.0,0,0,0,196.0,133.0,86.0,20.91,85.0,30.0,0

In [18]:
df= df_balanced

In [19]:
df['TenYearCHD'].value_counts()

TenYearCHD
1    3596
0    3596
Name: count, dtype: int64

In [20]:
df.corr()

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
male,1.000000,-0.018697,0.038889,0.236856,0.333529,-0.066488,-0.003351,-0.014287,0.020621,-0.098536,-0.033258,0.041087,0.037327,-0.083052,0.333529,0.136661
age,-0.018697,1.000000,-0.154375,-0.225294,-0.182983,0.127994,0.092997,0.325030,0.106555,0.187662,0.390170,0.177436,0.098841,0.001981,-0.182983,0.317565
education,0.038889,-0.154375,1.000000,0.008316,0.022935,-0.011704,-0.059772,-0.072769,-0.056606,0.011449,-0.112563,-0.032891,-0.144064,-0.053558,0.022935,-0.059179
currentSmoker,0.236856,-0.225294,0.008316,1.000000,0.775520,-0.068634,-0.045216,-0.130827,-0.077741,-0.047379,-0.129852,-0.099966,-0.162089,0.072205,0.775520,0.026419
cigsPerDay,0.333529,-0.182983,0.022935,0.775520,1.000000,-0.070984,-0.049305,-0.098128,-0.060111,-0.024039,-0.087511,-0.057788,-0.097832,0.087198,1.000000,0.082317
BPMeds,-0.066488,0.127994,-0.011704,-0.068634,-0.070984,1.000000,0.053811,0.270888,0.099618,0.099095,0.266466,0.182923,0.063115,0.081640,-0.070984,0.101235
prevalentStroke,-0.003351,0.092997,-0.059772,-0.045216,-0.049305,0.053811,1.000000,0.092849,0.017410,-0.030097,0.060669,0.054731,0.021810,-0.009760,-0.049305,0.070722
prevalentHyp,-0.014287,0.325030,-0.072769,-0.130827,-0.098128,0.270888,0.092849,1.000000,0.088819,0.135859,0.688891,0.591996,0.269222,0.146676,-0.098128,0.222957
diabetes,0.020621,0.106555,-0.056606,-0.077741,-0.060111,0.099618,0.017410,0.088819,1.000000,0.058486,0.121876,0.053237,0.091043,0.076115,-0.060111,0.110067
totChol,-0.098536,0.187662,0.011449,-0.047379,-0.024039,0.099095,-0.030097,0.135859,0.058486,1.000000,0.170519,0.128399,0.090058,0.082621,-0.024039,0.111174
sysBP,-0.033258,0.390170,-0.112563,-0.129852,-0.087511,0.266466,0.060669,0.688891,0.121876,0.170519,1.000000,0.774596,0.310723,0.157789,-0.087511,0.261251
diaBP,0.041087,0.177436,-0.032891,-0.099966,-0.057788,0.182923,0.054731,0.591996,0.053237,0.128399,0.774596,1.000000,0.372920,0.167668,-0.057788,0.170631
BMI,0.037327,0.098841,-0.144064,-0.162089,-0.097832,0.063115,0.021810,0.269222,0.091043,0.090058,0.310723,0.372920,1.000000,0.090256,-0.097832,0.095302
heartRate,-0.083052,0.001981,-0.053558,0.072205,0.087198,0.081640,-0.009760,0.146676,0.076115,0.082621,0.157789,0.167668,0.090256,1.000000,0.087198,0.034600
glucose,0.333529,-0.182983,0.022935,0.775520,1.000000,-0.070984,-0.049305,-0.098128,-0.060111,-0.024039,-0.087511,-0.057788,-0.097832,0.087198,1.000000,0.082317
TenYearCHD,0.136661,0.317565,-0.059179,0.026419,0.082317,0.101235,0.070722,0.222957,0.110067,0.111174,0.261251,0.170631,0.095302,0.034600,0.082317,1.000000

### pre-processing

In [21]:
# split data into x and y
x = df[['age', 'prevalentHyp', 'sysBP']]
y = df['TenYearCHD']

In [22]:
# split the data into train and test
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.7, random_state=123456)

### train the models

#### Decision Tree

In [23]:
from sklearn.tree import DecisionTreeClassifier

def create_model_decision_tree():
    model = DecisionTreeClassifier(max_depth=50)
    model.fit(x_train, y_train)
    return model

#### Random Forest

In [24]:
from sklearn.ensemble import RandomForestClassifier

def create_model_random_forest():
    model = RandomForestClassifier(n_estimators=100)
    model.fit(x_train, y_train)
    return model

#### CAT Boost

In [25]:
from catboost import CatBoostClassifier

def create_model_catboost():
    model = CatBoostClassifier(logging_level='Silent')
    model.fit(x_train, y_train)
    return model

#### AdaBoost

In [26]:
from sklearn.ensemble import AdaBoostClassifier

def create_model_ada_boost():
    model = AdaBoostClassifier()
    model.fit(x_train, y_train)
    return model

#### XGBoost

In [27]:
from xgboost import XGBClassifier

def create_model_xgboost():
    model = XGBClassifier()
    model.fit(x_train, y_train)
    return model

### model evaluation

In [28]:
from sklearn.metrics import confusion_matrix,accuracy_score, precision_score, recall_score, f1_score

def evaluate_model(model):
    # training accuracry
    y_pred = model.predict(x_train)
    y_true = y_train

    # calculate training accuracy
    training_accuracy = accuracy_score(y_true, y_pred)

    # testing accuracy
    y_pred = model.predict(x_test)
    y_true = y_test

    print(confusion_matrix(y_true, y_pred))

    # get the performance metrics for testing
    testing_accuracy = accuracy_score(y_true, y_pred)
    testing_precision = precision_score(y_true, y_pred,average='micro')
    testing_recall = recall_score(y_true, y_pred,average='micro')
    testing_f1 = f1_score(y_true, y_pred,average='micro')

    return training_accuracy, testing_accuracy, testing_precision, testing_recall, testing_f1

### generate performance chart

In [29]:
models = [
    ("Decision Tree", create_model_decision_tree(), (0, 0)),
    ("Random Forest", create_model_random_forest(), (0, 1)),
    ("CAT Boost", create_model_catboost(), (1, 0)),
    ("Ada Boost", create_model_ada_boost(), (1, 1)),
    ("XGBoost", create_model_xgboost(), (2, 0))
]

In [30]:
performance_data = []
for model_name, model, position in models:
    train_accuracy, test_accuracy, precision, recall, f1 = evaluate_model(model)
    performance_data.append([
        model_name, f"{train_accuracy * 100:0.2f}%", f"{test_accuracy * 100:0.2f}%", precision, recall, f1
    ])
    
performance_chart = pd.DataFrame(performance_data, 
            columns=["Model", "Train Accuracy", "Test Accuracy", "Precision", "Recall", "F1"])
performance_chart

[[ 810  245]
 [  72 1031]]
[[ 830  225]
 [  64 1039]]
[[738 317]
 [262 841]]
[[668 387]
 [372 731]]
[[745 310]
 [210 893]]

           Model Train Accuracy Test Accuracy  Precision    Recall        F1
0  Decision Tree         94.40%        85.31%   0.853105  0.853105  0.853105
1  Random Forest         94.40%        86.61%   0.866080  0.866080  0.866080
2      CAT Boost         76.62%        73.17%   0.731696  0.731696  0.731696
3      Ada Boost         66.73%        64.83%   0.648285  0.648285  0.648285
4        XGBoost         84.88%        75.90%   0.759036  0.759036  0.759036